### ISSUE TITLE
rpm INFO display confusing about webmin repo

### ISSUE THREAD

**Issue by verne-work** [virtualmin/virtualmin-release#2]
not sure if the Redhat/CentOS package virtualmin-release.noarch is still valid, or to be used standalone ...

but when I do a

`yum info virtualmin-release.noarch`

I see

> Installed Packages
> Name         : virtualmin-release
> Version      : 6.0
> Release      : 3.gpl
> Architecture : noarch
> Size         : 6.4 k
> Source       : virtualmin-release-6.0-3.gpl.src.rpm
> Repository   : @System
> Summary      : Virtualmin release file and package configuration for Virtualmin GPL
> License      : Copyright 2005-2017 Virtualmin, Inc.
> Description  : Virtualmin release file. This package also contains yum configuration to
>              : use the virtualmin.com provided rpm packages, as well as the public gpg key
>              : used to sign them.  It also installs the Webmin public key, so automatic
>              : upgrades of Webmin from webmin.com will have valid keys.
> 

I could be way too picky here --- please forgive me --- as recent posts on the forums make it clear that a Virtualmin environment should only update webmin from the virtualmin repo, NOT from webmin.com as mentioned above  :smile:

**Comment by swelljoe** [comment]
Resolved by #4
